
libducati =   ducati/ducatienabler.o  ducati/ducati_mmu.o ducati/hw_mmu.o


obj-$(CONFIG_BRIDGE_DUCATI)    += ducati_enabler.o
ducati_enabler-objs = $(libducati)


ccflags-y += -Wno-strict-prototypes

#Machine dependent
ccflags-y += -D_TI_ -D_DB_TIOMAP -DTMS32060 \
                -DTICFG_PROC_VER -DTICFG_EVM_TYPE -DCHNL_SMCLASS \
                -DCHNL_MESSAGES -DUSE_LEVEL_1_MACROS  \
                -DCONFIG_DISABLE_BRIDGE_PM -DDSP_TRACEBUF_DISABLED \
				-DDEBUG_DUCATI_IPC

#Header files

ccflags-y += -Idrivers/dsp/syslink/ducatienabler/inc
ccflags-y += -Iarch/arm/plat-omap/include
ccflags-y += -Idrivers/dsp/syslink/inc



