

libomap_mailbox = hw_mbox.o notify_dispatcher.o hw_ocp.o \
                  notify_mbxDriver.o drv_notifymbxdrv.o




obj-$(CONFIG_BRIDGE_MAILBOX) += notify_mailbox.o
notify_mailbox-objs = $(libomap_mailbox) 


ccflags-y += -Wno-strict-prototypes

#Machine dependent
ccflags-y += -D_TI_ -D_DB_TIOMAP -DTMS32060 \
                -DTICFG_PROC_VER -DTICFG_EVM_TYPE -DCHNL_SMCLASS \
                -DCHNL_MESSAGES -DUSE_LEVEL_1_MACROS  \
                -DCONFIG_DISABLE_BRIDGE_PM -DDSP_TRACEBUF_DISABLED \
		-DVPOM4430_1_06

#Header files
ccflags-y += -Idrivers/dsp/syslink/inc

